// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/record/stats": {
            "get": {
                "description": "按（时间区间）查询访问情况",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Record"
                ],
                "summary": "查询访问情况",
                "parameters": [
                    {
                        "type": "string",
                        "example": "2023-07-26",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "2023-07-24",
                        "name": "start_date",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/token/add": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "添加token信息,仅owener角色用户可用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "添加token信息",
                "parameters": [
                    {
                        "description": "token info",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/token.AddRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/token/delete": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "删除token信息,仅owener角色用户可用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "删除token信息",
                "parameters": [
                    {
                        "description": "id",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/token.DelRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/token/detail": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "获取token详情",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "获取详情",
                "parameters": [
                    {
                        "type": "string",
                        "example": "eth",
                        "name": "chainId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "0x429D83Bb0DCB8cdd5311e34680ADC8B12070a07f",
                        "name": "token",
                        "in": "query"
                    }
                ],
                "responses": {}
            }
        },
        "/token/edit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "修改token信息",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Token"
                ],
                "summary": "修改token信息，,仅owener角色用户可用",
                "parameters": [
                    {
                        "description": "id",
                        "name": "token",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/token.EditRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/login": {
            "post": {
                "description": "登陆获取token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "登陆",
                "parameters": [
                    {
                        "description": "Login information",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.LoginRequest"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/user/logout": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "登出账号（将token放入黑名单）",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "登出",
                "responses": {}
            }
        }
    },
    "definitions": {
        "token.AddRequest": {
            "type": "object",
            "properties": {
                "chainId": {
                    "type": "string",
                    "example": "eth"
                },
                "decimals": {
                    "type": "integer",
                    "example": 18
                },
                "symbol": {
                    "type": "string",
                    "example": "PLTC"
                },
                "token": {
                    "type": "string",
                    "example": "0x429D83Bb0DCB8cdd5311e34680ADC8B12070a07f"
                }
            }
        },
        "token.DelRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "1"
                }
            }
        },
        "token.EditRequest": {
            "type": "object",
            "properties": {
                "chainId": {
                    "type": "string",
                    "example": "eth"
                },
                "decimals": {
                    "type": "integer",
                    "example": 18
                },
                "id": {
                    "type": "string",
                    "example": "1"
                },
                "symbol": {
                    "type": "string",
                    "example": "PLTC"
                },
                "token": {
                    "type": "string",
                    "example": "0x429D83Bb0DCB8cdd5311e34680ADC8B12070a07f"
                }
            }
        },
        "user.LoginRequest": {
            "type": "object",
            "properties": {
                "key": {
                    "type": "string",
                    "example": "dodo"
                },
                "secrert": {
                    "type": "string",
                    "example": "721c6ff80a6d3e4ad4ffa52a04c60085"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "将login返回的token填在这里.",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
